routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\PostController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['prefix' => 'post','as' => 'post.'],function(){
Route::get('/',[PostController::class,'findAll'])->name('index');
Route::post('save/',[PostController::class,'storeOrUpdate'])->name('save');
Route::put('update/{id}',[PostController::class,'storeOrUpdate'])->name('update');
Route::get('delete/{id}',[PostController::class,'delete'])->name('delete');
Route::get('/{id}',[PostController::class,'getById'])->name('view');
});

app/Models/Contact.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Contact extends Model
{
    use HasFactory;

    protected $guarded = [];
}

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasFactory;
    protected $guarded=[];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/ContactController.php
<?php

namespace App\Http\Controllers;

use App\Repositories\ContactRepository;
use Illuminate\Http\Request;


class ContactController extends Controller
{
    private $contactRepository;

    public function __construct(ContactRepository $contactRepository)
    {
        $this->contactRepository = $contactRepository;
    }

    public function index(){
        $contact = $this->contactRepository->getAll();
        return $contact;
    }

    public function getById($id){
        $contact = $this->contactRepository->findById($id);
        return $contact;
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Exception;
use App\Services\PostService;
use PhpParser\Node\Stmt\TryCatch;

use function PHPUnit\Framework\isNull;

class PostController extends Controller
{
    protected $postService;

    public function __construct(PostService $postService)
    {
        $this->postService = $postService;
    }

    public function findAll(){
        $result = ['status' => 200];
        try{
            $result['data'] = $this->postService->getAll();

        }
        catch(Exception $e){
                $result = [
                    'status' => 500,
                    'message' => $e->getMessage()
                ];
        }
        //return response()->json($result,$result['status']);
        return view('post.index-post',['posts' => $result['data']]);
    }

    public function getById($id){
        $post = $this->postService->findById($id);
        return view('post.edit-post',['post' => $post]);
    }

    public function storeOrUpdate(Request $request,$id = null){
        $data = $request->only([
        'title',
        'description'
        ]);

        $result = ['status' => 201];
        try{
            if(!isNull($id) or $id != ""){
                $result['data'] = $this->postService->update($id,$data);
                $result['message'] = 'data with id '.$id.' updated';
            }
            else{
            $result['data'] = $this->postService->saveData($data);
            $result['message'] = 'data with id '.$result['data']['id']. ' created';
        }
        }
        catch(Exception $e){
            $result = [
                'status' => 500,
                'message' => $e->getMessage()
            ];
        }
        return redirect('/post')->with('message',''.$result['message']);
    }

    public function delete($id){
        if ($this->postService->deleteService($id)){
            return redirect('/post')->with('message','Data with id '.$id.' deleted');
        }
        else {
            echo "delete failed";
        }
    }



}

resources/views/layouts/master.blade.php
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.21.1/axios.min.js" integrity="sha512-bZS47S7sPOxkjU/4Bt0zrhEtWx0y0CRkhEp8IckzK+ltifIIE9EMIMTuT/mEzoIMewUINruDBIR/jJnbguonqQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <title>@yield('title')</title>
</head>
<body>
<div class="container mt-5">
    @if(session()->has('message'))
        <div class="message"><h1>{{ session()->get('message') }}</h1></div>
    @endif
    @yield('main_content')
</div>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

@stack('script')
</body>
</html>

resources/views/post/edit-post.blade.php
@extends('layouts.master')
@section('title' ,'Edit')
@section('main_content')
    <div class="row justify-content-center">
        <div class="col-6">
            <h2 class="text-center">Edit Post</h2>
            <hr>
            <form action="{{route('post.update',$post->id)}}" method="post">
                @csrf
                @method('PUT')
                <div class="form-group">
                    <input type="text" class="form-control" name="title"value="{{$post->title}}" required>
                </div>
                <div class="form-group">
                    <input type="text" class="form-control" name="description" value="{{$post->description}}" required>
                </div>
                <div class="form-group">
                    <button class="btn btn-block btn-success">Save Data</button>
                </div>
            </form>
            <a href ="{{route('post.index')}}" class="btn btn-block btn-info">Back</a>
        </div>
    </div>
@stop

resources/views/post/index-post.blade.php
@extends('layouts.master')
@section('title' ,'Home')
@section('main_content')
    <div class="row">
        <div class="col-12">

            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
                Add New Data
            </button>
            <hr>
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>Id</th>
                    <th>Title</th>
                    <th>Description</th>
                </tr>
                </thead>
                <tbody>
                @forelse($posts as $post)
                    <tr>

                        <td>{{$post->id}}</td>
                        <td>{{$post->title}}</td>
                        <td>{{$post->description}}</td>
                        <td>
                            <a href="{{route('post.view',$post->id)}}" class="btn btn-sm btn-info">Edit</a>
                            <a href="{{route('post.delete',$post->id)}}" class="btn btn-sm btn-danger">Trash</a>
                        </td>
                    </tr>
                @empty
                @endforelse
                </tbody>
            </table>
            <hr>
                   </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Add New Data</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form action="{{route('post.save')}}" method="post">
                        @csrf
                        <div class="form-group">
                            <input type="text" class="form-control" name="title" placeholder="Enter Title" required>
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control" name="description" placeholder="Description" required>
                        </div>
                        <div class="form-group">
                            <button class="btn btn-block btn-success">Add New Data</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@stop